env:
  node: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  requireConfigFile: false
rules:
  no-console: off
  radix: off
  import/prefer-default-export: off
