version: 2

jobs:
  build-nodejs:
    working_directory: ~/burst-compute
  
    docker:
      - image: cimg/node:16.20.2

    steps:
      - checkout

      - restore_cache:
          keys: 
            - burst-compute-nodejs-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - burst-compute-nodejs
      
      - run: npm install
      
      - save_cache:
          key: burst-compute-nodejs-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run sls package

      - run: npx eslint src/main/nodejs

workflows:
  version: 2
  build:
    jobs:
      - build-nodejs:
          filters:
            branches:
              only: master
